---
- name: CONFIGURACION IPV6 EN UNA LOOPBACK
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
   - name: SET IPv6 IN LOOPBACK
     ios_config:
       parents: "interface loopback 33"
       lines:
         - description IPv6 ADDRESS
         - ipv6 address 3001:ABCD:ABCD:1::1/128
         - ipv6 address FE80::1 link-local

   - name: SHOW IPv6 INTERFACE BRIEF 
     ios_command:
       commands:
         - show ip int bri
     register: output

   - name: SAVE OUTPUT ./ios_configurations/
     copy: 
       content: "{{ output.stdout[0] }}"
       dest: "ios_configurations/IPv6_output_{{ inventory_hostname }}.txt"

# través de Ansible, deberá crear un playbook que permita asignar direccionamiento IPv6 3001:ABCD:ABCD:1::1/128 y link
#local FE80::1 a la interfaz loopback 33

#Comando para que corra el codigo: "ansible-playbook -v cisco_router_IPv6_config_playbook.yml"
