print("-------------------")
print(" Integrantes: ")
print("-------------------")
print("- Abraham Gallardo")
print("- Rodrigo Sanhueza")
print("- Cristobal Escala")
print("\n")
input("Presione Enter para salir.")